apiVersion: apps/v1 # API version, v1 is stable for deployments
kind: Deployment    # To allow creation of pods
metadata:
  name: acmeair-booking-bookflights-deployment
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: acmeair
      tier: booking-bookflights
  template:
    metadata:
      annotations:
        vpa.k8s.io/in-place-update-policy: "true"
      labels:
        app: acmeair
        tier: booking-bookflights
    spec:
      hostAliases:
        - ip: "34.118.230.53"
          hostnames:
          - "mongohost"
        - ip: "34.118.231.131"
          hostnames:
          - "haproxy"
      dnsPolicy: Default # ClusterFirst
      containers:
        - name: acmeair-booking-bookflights-container
          image: rpizziol/acmeair-bookingservice-springboot:0.17
          imagePullPolicy: Always
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m" # Recommended to use the m notation
            limits:
              memory: "1Gi"
              cpu: "1000m" # 16000m
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0 # Immediate probes
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          lifecycle:
            preStop:
              exec:
                command: [ "pkill", "-15", "-f", "k8testpod" ]