apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acmeair
      tier: mongo
  template:
    metadata:
      annotations:
        vpa.k8s.io/in-place-update-policy: "true"
      labels:
        app: acmeair
        tier: mongo
    spec:
      hostAliases:
        - ip: "34.118.230.53"
          hostnames:
          - "mongohost"
        - ip: "34.118.231.131"
          hostnames:
          - "haproxy"
      dnsPolicy: Default # ClusterFirst
      containers:
        - name: mongo-container
          image: rpizziol/acmeair-mongo-database:0.03
          imagePullPolicy: Always
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 27017
