apiVersion: v1
kind: Service
metadata:
  name: flightgetrewardmiles
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: flight-getrewardmiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
