apiVersion: v1
kind: Service
metadata:
  name: bookingcancelbooking
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: booking-cancelbooking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP #LoadBalancer

