apiVersion: v1
kind: Service
metadata:
  name: customerbyidget
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: customer-byidget
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP #LoadBalancer

