apiVersion: v1
kind: Service
metadata:
  name: flightqueryflights
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: flight-queryflights
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP #LoadBalancer

