apiVersion: v1
kind: Service
metadata:
  name: customervalidateid
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: customer-validateid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

