apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: haproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # ClusterIP

