apiVersion: v1
kind: Service
metadata:
  name: mongohost
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP #LoadBalancer

