apiVersion: v1
kind: Service
metadata:
  name: customerupdatemiles
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: customer-updatemiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP #ClusterIP

